name: Run continuous integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: printenv

      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v4
        with:
          dependency-graph: generate-and-submit

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_READ_PACKAGE }}

      - name: Publish artifact
        if: github.event_name == 'push'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}