name: Integration Test

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: temurin
        cache: gradle

    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/actions/setup-gradle@v4
      with:
        dependency-graph: generate-and-submit

    - name: Build with Gradle
      run: ./gradlew check
      env:
        GITHUB_TOKEN_READ_PKG: ${{ secrets.ACTION_READ_PACKAGE }}
        GITHUB_TOKEN: ${{ secrets.ACTION_READ_PACKAGE }}