name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    if: ${{ !github.event.release.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Project Info
        id: info
        run: |
          echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Build and Publish with Gradle
        run: ./gradlew publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ github.event.release.tag_name }}
